### ISSUE TITLE
Unpacking syntax within formal parameters of functions?

### ISSUE THREAD

**Issue by aalok-sathe** [yawgmoth/pyhanabi#1]
I ran into an error trying to run your code, and can't say I've seen this syntax for specifying unpacked formal params in Python functions before.
```python
python3.8 httpui.py 
  File "httpui.py", line 104
    def make_board_image((i,card)):
                         ^
SyntaxError: invalid syntax
```

What version Python do you use? Do you use any particular flavor of Python?

**Comment by aalok-sathe** [comment]
I just realized this works with Python2.

**Comment by yawgmoth** [comment]
You are right that this project was done in Python 2, and the tuple unpacking was removed in python 3. 2to3 does a reasonable job at converting the code, but the http server requires some changes to properly use bytestrings, if memory serves. Unfortunately I have not had the time to properly convert and test the code yet.
